minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@shun-shobon/style-guide"

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

saveExact: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
