name: changesets

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  changesets:
    runs-on: ubuntu-slim
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup | Node.js
        uses: ./.github/actions/setup-node

      - name: Setup | GitHub App
        id: app-token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Run | Changesets
        uses: changesets/action@63a615b9cd06ba9a3e6d13796c7fbcb080a60a0b # v1.8.0
        with:
          title: "chore(release): publish"
          commit: "chore(release): publish"
          version: pnpm version-package
          publish: pnpm release
          commitMode: github-api
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
