name: check
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup | Node.js
        uses: ./.github/actions/setup-node

      - name: Run | Lint
        run: pnpm run lint

  format:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup | Node.js
        uses: ./.github/actions/setup-node

      - name: Run | Format
        run: pnpm run format:check

  test:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup | Node.js
        uses: ./.github/actions/setup-node

      - name: Run | Test
        run: pnpm run test:ci

      - name: Finish | Codecov
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json
          fail_ci_if_error: true
